name: pond-it-1.3
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.*
- pip
- numpy
- seaborn
- matplotlib=3.0.*
- pandas
- scipy
- notebook
- openpyxl
# - pywin32
# - pip:
#   - matplotlib>=3.0.0<4.0.0
#   - seaborn>=0.9.0<0.10.0