name: pond-it
channels: !!python/tuple
- defaults
- conda-forge
dependencies:
- python=3.5.*
- pip
- numpy
- seaborn
- matplotlib=3.*
- pandas
- scipy
- notebook
- xlrd
# - pip:
#   - matplotlib>=3.0.0<4.0.0
#   - seaborn>=0.9.0<0.10.0